### ISSUE TITLE
Coale-Demeny Model Life Tables not working

### ISSUE THREAD

**Issue by mpascariu** [hanase/demogR#2]
Hi Hana,

Please check the Coale-Demeny functions. Some of them are returning errors.

Reproducible example:

```R
> # Thu Aug  2 14:41:46 2018 ------------------------------
> library(demogR)
> 
> cdmlte()
Error in cdmlte() : could not find function "cdmlte"
> cdmltn()
Error in cdmltn() : could not find function "cdmltn"
> cdmlts()
Error in cdmlts() : could not find function "cdmlts"
>
```

Marius

**Comment by hanase** [comment]
@mpascariu Good catch Marius! These functions for some reason never made it to the NAMESPACE. I fixed it and submitted a new version to CRAN now (0.5.1). Until it gets up, you can use demogR:::cdmlte(). Thanks again for reporting it!
