### ISSUE TITLE
Issues When Using Coale-Demeny West Table

### ISSUE THREAD

**Issue by Wilsonnn245** [hanase/demogR#7]
Hi Hana, 
I'm trying to model mortality data with the Brass Relational Logit using the Coale-Demeny West Model Life Table as the standard. However, I'm facing some issues while working on my research:

1. I've noticed that the last age group in the package is ages 95+, however my data is only up to 85+. I'm thinking of using the age-group from the model life table up to the age-group of 85-90 but it would seem to be inaccurate since I would be neglecting the mortality of those ages 90 and above while the using the life table. Is there anyway for me to consolidate the last 3 age-groups in the model life table (85-90, 90-95, 95+) into only 1 age group (85+)? Please advice on how I should move forward :)

2. Another issue is that I'm modeling mortality data for the male, female and total population. However, from the demogR package I would only be able to access the model life table for male and female population. Is there any methods that I can use to construct the model life table for the total population based on the existing gender-specific life table? 

Appreciate your help and input on the above matters. Thanks in advance!

**Comment by hanase** [comment]
Re 1., it depends which columns of the life table you're interested in. You can look at [how this is done in MortCast]( https://github.com/PPgp/MortCast/blob/master/R/life_table.R#L87) where `nresage` is the last open age group in the truncated table, i.e. in you case 85+. Using that code, for most columns one would keep values from the untruncated life table for up to age group 80-85 and modify the last age group (85+). For the s(x) column, one would also modify the  80-85 age group.

Re 2., I don't know, but it would again depend on the indicator.
